### ISSUE TITLE
understanding token expiration

### ISSUE THREAD

**Issue by ericgj** [googlesamples/apps-script-oauth2#24]
I have several scripts that use this library to trigger service calls on form submit (in the responses sheet). The end users do not authorize this script, since they don't directly access the responses sheet -- it is intended to "run in the background". The problem is, every couple weeks it seems the token expires, and I have to manually reset the user properties and re-authorize. The service is the Google App Engine Task Queue.

Is this expected behavior / is there any way around this?  I am requesting offline access -- `.setParam('access_type', 'offline')` -- so shouldn't the token get refreshed?

I saw this discussed in #20, but wasn't sure if it applied to my situation and in any case I didn't understand the solution to "revoke access for this script / project and reauthorize" . I understand reauthorize. How do you revoke access?  

I think something about this should be added to the README given there are a number of issues asking about expired tokens. I would be happy to propose something once I understand the solution(s).

Thanks!

**Comment by mihaiaperghis** [comment]
I noticed something that may be related to this:

I'm using an onOpen(e) trigger to automatically display a sidebar that requires access to a Google API. When I first open the document, the sidebar displays the message requiring me to authorize, even if there already is an access token and refresh token in my user properties.

If I then go ahead and re-render the sidebar (via a menu item), the message disappears and I get the correct data. However, if I don't try to re-render the sidebar and click the Authorize link instead, I'll receive a new access token and my refresh token will be deleted (which means that in one hour I'll have to manually re-authorize).

I tested removing the onOpen(e) trigger, refreshing the spreadsheet and manually displaying the sidebar via the menu, and that seems to work with no issues.

I guess the only reason this happens is that the user properties are initiated after the onOpen(e) trigger, so that getOAuthService() doesn't see the access token and assumes I'm not authorized.

**Comment by erickoledadevrel** [comment]
Google's OAuth2 implementation only returns a refresh_token the first time you authorize, even if you continue to request offline access. Information on how to revoke a Google OAuth2 token is available here:

https://developers.google.com/identity/protocols/OAuth2WebServer#tokenrevoke

The refresh() flow in the library takes effort to preserve the refresh_token, but not if you go through the authentication flow again. I'm not sure it's always safe to assume that existing refresh tokens should be  preserved when re-authorizing, so I'm wary to add it.

**Comment by mihaiaperghis** [comment]
Would be useful then to mention the "onOpen + getOAuthService" scenario in the docs, since it's a scenario when a user might get the Authorize message despite being already authorized (thus leading to a case where the refresh_token gets removed).
