### ISSUE TITLE
Service Accounts

### ISSUE THREAD

**Issue by JohnGale87** [googlesamples/apps-script-oauth2#39]
When using service accounts if you are changing the subject between calls it always works for the first subject and then returns a 401 for all subsequent subjects.

The service name is saved to the PropertyService provided when calling "createService" if you change the subject but use the same service name the token retrieved from the property service is the same as for the first subject.

To work around this I added the subject name into the service name when creating the service. 

But now i'm concerned about having properties cluttering up the property service that i wont need.

**Comment by erickoledadevrel** [comment]
This is working as intended, and the service account sample also shows appending the user's email to the service name:

https://github.com/googlesamples/apps-script-oauth2/blob/master/samples/GoogleServiceAccount.gs#L36

Having access tokens for different users saved to the same property could be dangerous, for example if multiple executions of your script were happening at the same time.

Script properties are limited to 500K total, so if you have a lot of users you are operating on I could see how that could be a concern. One potential solution would be to use an in-memory property store, which I've already created for the OAuth1 library:

https://github.com/googlesamples/apps-script-oauth1/blob/master/MemoryProperties.gs

If you are doing this, make sure to set a cache for your service, so that new access tokens are only retrieved when needed.
