### ISSUE TITLE
A 3d-party service can't re-send the state parameter from RFC.

### ISSUE THREAD

**Issue by oshliaer** [googlesamples/apps-script-oauth2#48]
Hi! I'm feeling stuck with StateTokenBuilder and the oAuth2 authority service. This service can't re-send me the `state` parameter. I've wrote them and they told that the `state` parameter isn't required from RFC. It's just a recommended parameter.

In this case I always get `The state token is invalid or has expired. Please try again.`  message.

I know this but I'm not feeling easier. I have to ask my users for an additional transition to login. This is extremely inconvenient.

Are there any ideas to avoid this? Can I catch the StateTokenBuilder workflow and put to it the `state` from the properties service?

Best wishes!

**Comment by erickoledadevrel** [comment]
Which OAuth2 provider are you trying to connect to? 

One possible solution we be to use the tactic the Apps Script OAuth1 library uses, namely to append the state parameter to your redirect URI:

https://github.com/googlesamples/apps-script-oauth1/blob/master/Service.gs#L518

So instead of relying on the OAuth provider to read the state parameter and send it back when it does the redirect, you merely append it directly to your redirect URI. This may not work if the full redirect URI needs to be registered ahead of time, since the state token changes for each request.

**Comment by oshliaer** [comment]
I'm using the Yandex.Money API with their oAuth. They don't use `state`. 
Ok. I try to pass the redirect uri. Thanks.
Don't close this topic for a week please. I think I can solve this problem.

**Comment by sdooleyFJUHSD** [comment]
I don't know if my problem is the same, but the error I get _is_ the same. I'm trying to get a Google email address.

In testing, everything works great. Buttons are clicked, tokens are exchanged, magic is made and emails are logged, all as expected when using _my_ account, but when I publish and test with another account I get:

> The state token is invalid or has expired. Please try again.

When I change...

> "Execute the app as: Me"

 to...

> "Execute the app as: User accessing the web app"

...the second test account works, but I get no results on my end (obviously). This seems like a pretty normal thing to attempt, so what am I doing wrong?

I'm pretty much using code straight off of [samples/GooglePlus.gs](https://github.com/googlesamples/apps-script-oauth2/blob/master/samples/GooglePlus.gs)

[Here's the web-app.](https://script.google.com/macros/s/AKfycbzv93m75cHEOj-3l_oNz5tJEY3Lnz2rQzStg_oaxQH7fQa78vg/exec)

**Comment by erickoledadevrel** [comment]
@sdooleyFJUHSD That is a separate issue. The library won't work for the scenario where the web app is deployed as the developer. This is because the state token forged when you get the Authorization URL has the developer's identity, but when the user gits the /usercallback URL is uses their identity.

Closing this issue since it's been a couple of weeks.

**Comment by oshliaer** [comment]
Ok. It is solved with a internal browser's communicate library like Intercom.js https://github.com/googlesamples/apps-script-oauth2/tree/master/samples/Add-on
