### ISSUE TITLE
Duplicate Namespace Including Library

### ISSUE THREAD

**Issue by stvkas** [googlesamples/apps-script-oauth2#70]
I'm trying to issue a pull request to extend this library to the Medium API, but I'm having a hard time testing my library change with the sample apps because Google Apps Script is namespacing my fork in a weird way. I've documented it all in [this Stack Overflow question](https://stackoverflow.com/questions/44596020/duplicate-namespace-including-google-apps-script-library) since I think it's more of a platform issue. SO has been silent for four days now, so does someone familiar with this library will know what's going on?

**Comment by oshliaer** [comment]
Hi @stvkas 

Please look at [the original library's file](https://script.google.com/d/1B7FSrk5Zi6L1rSxxTDgDEUsPzlukDsi4KGuTMorsTQHhGBzBkMun4iDF/edit?usp=sharing). It's not like your code. For building code like yours it uses [gulp-expose](https://www.npmjs.com/package/gulp-expose) for exporting and isolation main code.

When you need to build a new library you have to use the ['src' directory](https://github.com/googlesamples/apps-script-oauth2/tree/master/src) as a source. This means you want to modify the current library or improve your own. Otherwise if you want to use code directly (without libraries possibility, [for speed up](https://developers.google.com/apps-script/guides/libraries)) you can copy code from the [dist folder](https://github.com/googlesamples/apps-script-oauth2/tree/master/dist) directly.

The gulp-expose wraps the library [here](https://github.com/googlesamples/apps-script-oauth2/blob/master/dist/OAuth2.gs#L775).

It would be great to see your PR here.

> A script that uses a library does not run as quickly as it would if all the code were contained within a single script project. Although libraries can make development and maintenance more convenient, you should use them sparingly in projects where speed is critical. Because of this issue, library use should be limited in add-ons. _https://developers.google.com/apps-script/guides/libraries_

**Comment by stvkas** [comment]
Thanks for your help! I just posted my [PR](https://github.com/googlesamples/apps-script-oauth2/pull/72).
